import zhCn from 'element-plus/lib/locale/lang/zh-cn'
import {
  ElButton,
  ElCard,
  ElCol,
  ElForm,
  ElFormItem,
  ElInput,
  ElLoading,
  ElRow,
  ElContainer,
  ElAside,
  ElMain,
  ElHeader,
  ElSubmenu,
  ElMenu,
  ElMenuItem,
  ElTabPane,
  ElTabs,
  ElMenuItemGroup,
  ElDropdown,
  ElDropdownItem,
  ElTable,
  ElTableColumn,
  ElDropdownMenu,
  ElPagination,
  ElDialog,
  ElSelect,
  ElDatePicker,
  ElUpload,
  ElOption,
  ElTree,
  ElIcon,
  ElConfigProvider
} from 'element-plus'
export const components: any[] = [
  ElConfigProvider,
  ElTree,
  ElButton,
  ElRow,
  ElCol,
  ElTabPane,
  ElTabs,
  ElCard,
  ElForm,
  ElInput,
  ElSubmenu,
  ElMenu,
  ElDropdown,
  ElDropdownItem,
  ElSelect,
  { ElDatePicker, locale: zhCn },
  ElUpload,
  ElPagination,
  ElDropdownMenu,
  ElMenuItem,
  ElDialog,
  ElTable,
  ElOption,
  ElFormItem,
  ElTableColumn,
  ElMenuItemGroup,
  ElContainer,
  ElAside,
  ElMain,
  ElHeader,
  ElIcon
]
<<<<<<< HEAD
export const plugins: any[] = [ElLoading, ElMessage,ElDatePicker]
=======
export const plugins: any[] = [ElLoading]
>>>>>>> 51dd7e03e11b8e9d761c7a7f2619edd63c1ff31b
