import locale from 'element-plus/lib/locale/lang/zh-cn'
import {
  ElButton,
  ElCard,
  ElCol,
  ElCheckbox,
  ElCheckboxGroup,
  ElForm,
  ElFormItem,
  ElInput,
  ElLoading,
  ElRow,
  ElContainer,
  ElAside,
  ElMain,
  ElHeader,
  ElSubmenu,
  ElMenu,
  ElMenuItem,
  ElTabPane,
  ElTabs,
  ElMenuItemGroup,
  ElDropdown,
  ElDropdownItem,
  ElTable,
  ElTableColumn,

  ElDropdownMenu,
  ElPagination,
  ElDialog,
  ElSelect,
  ElDatePicker,
  ElUpload,
  ElOption,
  ElTree,
  ElIcon,
  ElRadio,
  ElRadioGroup
} from 'element-plus'
export const components: any[] = [
  ElTree,
  ElButton,
  ElRow,
  ElCol,
  ElCheckbox,
  ElCheckboxGroup,
  ElTabPane,
  ElTabs,
  ElCard,
  ElForm,
  ElInput,
  ElSubmenu,
  ElMenu,
  ElDropdown,
  ElDropdownItem,
  ElSelect,
  ElDatePicker,
  ElUpload,
  ElPagination,
  ElDropdownMenu,
  ElMenuItem,
  ElDialog,
  ElTable,
  ElOption,
  ElFormItem,
  ElTableColumn,
  ElMenuItemGroup,
  ElContainer,
  ElAside,
  ElMain,
  ElHeader,
  ElIcon,
  ElRadio,
  ElRadioGroup
]

// 插件和指令
import ContextMenu from '@imengyu/vue3-context-menu'
export const plugins: any[] = [ElLoading, ContextMenu]
